Improve error handling for missing plugins.
Before:

    $ sinntp pull -p foo
    Traceback (most recent call last):
      File ".../sinntp/./sinntp", line 349, in <module>
        base_command = BaseCommand(argv)
      File ".../sinntp/./sinntp", line 300, in __init__
        Command.__init__(self, argv)
      File ".../sinntp/./sinntp", line 123, in __init__
        plugin = getattr(plugins, name)
    AttributeError: module 'plugins' has no attribute 'foo'

After:

    $ sinntp pull -p foo
    usage:
      nntp-pull [options] groupname[>filename] [groupname[>filename] ...]
      nntp-push [options] [newsgroups...]
      nntp-get message-id
      nntp-list
    sinntp: error: no such plugin: 'foo'