Extend error message for failed nntplib import.
If it's Python >= 3.13, but standard-nntplib is not installed, say:

    ModuleNotFoundError: No module named 'nntplib'; https://pypi.org/project/standard-nntplib/ is required for Python >= 3.13

https://github.com/jwilk/sinntp/issues/19